language: generic
sudo: required
services:
  - docker

before_install:
  - docker build  -t dbaneman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dbaneman/docker-react npm run test
